### ISSUE TITLE
standoff markup

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#154]
we promise standoff markup ar various places, but we never are specific how this can be written in DOL. What would be the way to specify this?

**Comment by clange** [comment]
Standoff markup means that you point into something from externally, i.e. that you do not make annotations inside a DOL file, but that you make them externally, e.g. using RDF. All that DOL has to provide for this is identifying all relevant things with URIs, so that one can talk about these things even when outside of a DOL file. But I will check all occurrences of "standoff markup".

**Comment by tillmo** [comment]
so it seems that we do not need to change anything in the DOL document (modulo your check...)

**Comment by clange** [comment]
Indeed with one of the commits I pushed recently (can't link to it from
this limited email interface) I addressed all standoff markup issues.

-- 
Christoph Lange(-Bever)
http://langec.wordpress.com/about
Sent from a mobile device; please excuse my brevity.

**Comment by tillmo** [comment]
OK, I think this is the commit that solves the issue: ba1770f1d3a4cea4bb39b987040223217cd1f47f
