### ISSUE TITLE
prefix in examples 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/DOL#161]
we need to define ":lang", which is used to identify languages

**Comment by gnn** [comment]
Note to self: this means I have to read the standard and see where :lang is used and how.

**Comment by gnn** [comment]
Requesting a review: the solution is short but maybe too simple.
Also, is the missing definition for the "ser:" prefix a problem, too?

**Comment by tillmo** [comment]
yes, there should also be a prefix for "ser:".

**Comment by gnn** [comment]
I closed this but I came across two minor issues which I wasn't really able to resolve:

  * on line 2882 an undeclared "trans:" prefix is used. I guess that's OK though, as it's in an intentionally incomplete example.
  * on line 9189 there's a similar problem with a "log:" albeit in a small but complete example. The problem here is that directly above this on line 9174 the same logic is used without the "log:" prefix. I wasn't able to decide whether to remove the prefix in the lower line or whether to add and declare it.

Somebody else (@tillmo? Sorry, I know you're packed with issues) is better suited to decide this. I'm happy to carry out the decision though.
