### ISSUE TITLE
Do we need a property for "the logic of a view"?

### ISSUE THREAD

**Issue by clange** [tillmo/DOL#211]
The DOL Ontology so far has an object property `logic` for the logic of an OMS. However, inside a 'logic section' in the abstract syntax, there are also views.  Therefore, do we need another, analogous object property for 'the logic of a view'? Or should we extend the domain of the current property `logic` to cover the _union_ of `OMS` and `View`?

**Comment by tillmo** [comment]
The problem is that that there are also heterogeneous views, where the logics of the source and target OMS are different. Hence, I think that there is no useful concept of "logic of a view". There is only the logic of the source OMS, and the logic of the target OMS. The "logic pair" of the view could be defined as the pair of these logics. But I am not sure whether we need this.

Besides, we can also classify views into homogeneous and heterogeneous ones (depending on whether the two logics in the logic pair are equal or different). For homogeneous views, one could indeed define the "logic of the homogeneous view" to be the logic that occurs in both components of the pair.
