### ISSUE TITLE
should RFCs be referenced via chapter 3?

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#216]
Pere Rivett suggests that things like IETF/RFC 3987 should be referenced through chapter 3. However, I find this a bit cumbersome. Maybe write "IETF/RFC 3987, see clause 3"? @clange, do you have an idea?

**Comment by clange** [comment]
I do not have a _specific_ idea, but this problem is not limited to RFCs. For example, the 2nd example in the term definition "non-logical symbol" cites Common Logic as "ISO/IEC 24707:2007".

Should we instead cite all these as

    Common Logic [NR6]

or

    Common Logic ISO/IEC 24707:2007 [NR6]

?

(In any case I would be happy if someone else than me could take care of this.)

**Comment by tillmo** [comment]
I think we should use `Common Logic [NR6]`. @fabianneuhaus, do you agree?

**Comment by tillmo** [comment]
again: @fabianneuhaus, do you agree?

**Comment by tillmo** [comment]
again again: @fabianneuhaus, do you agree?
