### ISSUE TITLE
comments on namespacing 

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#230]
> 9.8 quotes the following namespace which seems inconsistent with the official one: http://www.omg.org/spec/DOL/1.0/xml namespace. 

Not sure what you mean by “the” official namespace. The namespace http://www.omg.org/spec/DOL/1.0/xml, which is mentioned in 9.8, is just an XML namespace that gives home to one XML attribute dol:id, which is intended to be used in XML serializations of existing ontology languages. The same namespace is mentioned in 2.2. It is different from the namespace http://www.omg.org/spec/DOL/dol-language/, the home of the implementation of DOL as an RDF vocabulary (a.k.a. “the DOL Ontology”). 

> uses xml:base at variance with the guidance in the specification document.

I don't understand this comment; can you please clarify? Or maybe this is a misunderstanding. If you are referring to the "Conformance of OWL/XML with DOL" section in B.1.2, that's about ontologies serialized in OWL/XML in general. The "OWL file" that we are discussing here is an OWL ontology serialized as RDF/XML (which is different from OWL/XML).

**Comment by clange** [comment]
@tillmo what would you like me to do about this?

The main text in the description of the issue is my response to comments from Pete Rivett (is he on GitHub?). On 2015-09-05 the last comment in this communication thread was that you (@tillmo) had asked @fabianneuhaus to forward my responses to Pete Rivett.

Direct communication between me and him might help now; however I'll have very little time between now and 15 October.

**Comment by tillmo** [comment]
you are right, we are waiting for Pete
