### ISSUE TITLE
annotations in the semantics of OMS definitions

### ISSUE THREAD

**Issue by mcodescu** [tillmo/DOL#286]
We have modified the semantics of OMS definitions such that the semantics of the OMS in every logic that is supported by the language is stored in the heterogeneous logical environment. A definition may have a conservativityStrength annotation. Does it apply to all model classes generated by the semantics (one for each logic)?

**Comment by tillmo** [comment]
Good question. I think for pragmatic reasons, I would let it only apply for the current logic (at OMS definition time). If someone puts an OMS in a different logical context, (s)he cannot assume that the annotations apply in the original way.
But when thinking about it, I think that our modification of the semantics of OMS definitions was a bit premature. Is it needed at all? My original example only concerned native documents, and then all this only concerns the function sem_{native} still to be introduced in section 10.2.
"Consider e.g. an OWL file stored at http://ontohub.org/repo/my-onto.owl. Now we can interpret this in OWL's default logic, namely SROIQ. However, we also can interpret it in OWL-Full. And this may make a difference. (A similar phenomenon can arise with RuleML.)
In DOL, we can distinguish and e.g. relate the two different cases as follows:
entailment my_entailment =
  { logic SROIQ  : http://ontohub.org/repo/my-onto.owl }
entails
  { logic OWL-Full : http://ontohub.org/repo/my-onto.owl }
end

The problem is now that we have to assign different loc/ids to { logic SROIQ  : http://ontohub.org/repo/my-onto.owl } and { logic OWL-Full : http://ontohub.org/repo/my-onto.owl }.
We need a scheme that allow us to include the logic selection into the IRI, e.g. http://ontohub.org/repo/my-onto.owl/logic=SROIQ.
Moreover, we have to sacrifice linked data principles a bit, since the two IRIs
http://ontohub.org/repo/my-onto.owl/logic=SROIQ
http://ontohub.org/repo/my-onto.owl/logic=OWL-Full
would denote two different ontologies, which however are based on the same file
http://ontohub.org/repo/my-onto.owl

Hence, I think we need to change the semantics of OMSReference a bit. The current logic should be appended to the IRI in the style shown above. "

**Comment by clange** [comment]
> Moreover, we have to sacrifice linked data principles a bit, since the two IRIs
http://ontohub.org/repo/my-onto.owl/logic=SROIQ
http://ontohub.org/repo/my-onto.owl/logic=OWL-Full
would denote two different ontologies, which however are based on the same file
http://ontohub.org/repo/my-onto.owl
I don't think this is a problem. Initially we'd serve from all of these IRIs the same data (i.e. just the OWL ontology, leaving implicit the question of what logic it is in), but later we could serve additional data:

Data to be served from http://ontohub.org/repo/my-onto.owl/logic=SROIQ (written down in RDF/Turtle):

    <http://ontohub.org/repo/my-onto.owl/logic=SROIQ> a dol:OMS ;
      dol:hasLogic log:SROIQ ;
      owl:sameAs <http://ontohub.org/repo/my-onto.owl> ;
      # ^ because SROIQ is the default logic

    # here, the rest of the ontology would follow.
    # Or one could look it up from my-onto.owl by following the owl:sameAs link
    # (which linked data clients commonly do).

Data to be served from http://ontohub.org/repo/my-onto.owl/logic=OWL-Full:

    <http://ontohub.org/repo/my-onto.owl/logic=OWL-Full> a dol:OMS ;
      dol:hasLogic log:OWL-Full .

    # here, the rest of the ontology would follow.

**Comment by tillmo** [comment]
agreed.

**Comment by tillmo** [comment]
In [428ff97], I have now used the notation http://ontohub.org/repo/my-onto.owl?logic=OWL-Full. Or would a / be better?
@mcodescu: [428ff97] contains a new ednote indicating the correct place where all logics supported by the given language need to be considered.

**Comment by tillmo** [comment]
@mcodescu: good, have seen your changes. I left one answer to an ednote.
