### ISSUE TITLE
Colon inconsistency

### ISSUE THREAD

**Issue by tillmo** [tillmo/DOL#341]
P28. The textual example illustrating section 7.2 contains two inconsistent language lang:CommonLogic terms, one of which is followed by a colon while the other is not.

see http://issues.omg.org/browse/DOL-38

**Comment by fabianneuhaus** [comment]
While trying to address this issue, I noticed that there is a problem with the example in section 7.2 that goes beyond a simple colon issue. The colon seems to be there because this is a language qualification. Language qualifications are allowed for group OMS. However, the grammar does not allow for a group OMS after "then", just an "ExtensionOMS"
Is this a bug in the grammar or in the example?

**Comment by tillmo** [comment]
good point. I rather would change the grammar here. Language and logic qualifications should be allowed as part of an `ExtensionOMS`. And when looking at #347, also `RelativeClosureOMS` should be allowed there.

**Comment by tillmo** [comment]
see 352_bug_in_example_in_7.2
Text for FTF: there was no inconsistency, because the two lang:CommonLogic terms were used in different syntactic roles (global versus local language qualification). Nevertheless, we have revised the example, such that this is avoided now.

**Comment by fabianneuhaus** [comment]
omg proposal added
