### ISSUE TITLE
How to handle SROIQ global restrictions?

### ISSUE THREAD

**Issue by okutz** [tillmo/DOL#82]
syntactic 'validity' of a SROIQ ontology is a global property; therefore a valid SROIQ ontology that imports another one might not be valid any more. 

The same applies to DOL structuring like unions, extensions, etc. 

Therefore, DOL structuring leads outside the logic.

**Comment by tillmo** [comment]
Appendix B now contains a remark:

Remark: strictly speaking, the institution defined above is
\emph{{OWL} 2 DL without restrictions} in the sense of
\cite{DBLP:conf/owled/SchneiderRS13}. The reason is that in an
institution, the sentences can be used for arbitary formation of
theories. This is related to the presence of DOL's union operator on
OMS.  OWL 2 DL's specific restrictions on theory formation can be
modeled \emph{inside} this institution, as a constraint on OMS.  This
constraint is generally not preserved under unions or
extensions. DOL's multi-logic capability allows the clean distinction
between ordinary OWL 2 DL and {OWL} 2 DL without restrictions.
