### ISSUE TITLE
empty CURIE must be made illegal

### ISSUE THREAD

**Issue by cmaeder** [tillmo/DOL#85]
```
CURIE     = [ Prefix ] , Reference ;
Reference = Path , [ Query ] , [ Fragment ] ;
Path      = ipath-absolute | ipath-rootless | ipath-empty ;
```

Currently a Path may be empty via ipath-empty. Empty names cannot be handled (at least not easily).
Therefore, if the Path is empty, then at least one of Prefix, Query or Fragment should be non-optional.

**Comment by tillmo** [comment]
The problem is that now the code no longer goes through ebnf/Ebnf (because this cannot deal with !! as separators). Could you please adapt this? For now, I have inserted a space before `\begin{lstlisting}`, causing ebnf/Ebnf to leave this alone (although this should not remain so).

**Comment by cmaeder** [comment]
If using parenthesis is the problem, than they can be avoided by a further non-terminal like

```
MaybeEmptyCURIE = [ Prefix ] , Reference  ;
CURIE = MaybeEmptyCURIE - ;
```

However, if you want to avoid the postfix `-` I would suggest

```
CURIE = NEReference | ( Prefix , [ NEReference ] ) ;
NEReference = NEPath | ( [ NEPath ] , Query) | ( [ NEPath ] , [ Query ] , Fragment ) ;
NEPath = ipath-absolute | ipath-rootless ;
```

(prefix `NE` indicating non-empty, and the non-terminals `Path` or `Reference` correspond to optional `NEPath` resp. `NEReference`). This maybe further rewritten to

```
CURIE = NEReference | PrefixedRef ;
PrefixedRef = Prefix , [ NEReference ] ;
NEReference = NEPath | QueryRef | FragRef ;
QueryRef = Path , Query ; 
FragRef = Path , [ Query ] , Fragment ;
Path = NEPath | ipath-empty ;
NEPath = ipath-absolute | ipath-rootless ;
```

**Comment by gnn** [comment]
Yes, using parens is the problem because they were used to escape back to latex.
@tillmo: are there any separators besides '<>' and '()' ebnf/EBNF could deal with. (From a cursory look at the sourece, maybe '+'?). If the answer is no, just do nothing, cause I pushed a fix using the 'one additional non-terminal method' anyway and I'll just leave it like that in this case. 
@cmaeder: many thanks for the comment. Especially the last one was a pleasure to read.
